### ISSUE TITLE
POI-PPT的代码结构疑问

### ISSUE THREAD

**Issue by LiYaHX** [qhm123/POI-Android#2]
你好，请问POI-PPT的代码结构是如何组成的？

我尝试将该工程中的源码（如：scratchpad）添加到我自己的Android工程中，总会报错。
错误如下：
（1）awt中的类不能正常被加载进来。
          如： import and.awt.image.BufferedImage;（error : The import and.awt.image cannot be resolved）
（2）scratchpad/src在目录结构不对。我自己的会将所有源码加载进来，而你的工程只加载了部分源码。请问我该如何做才能做到你那样？

我添加源码的方式如下：
（1）将源码拷贝进工程；
（2）右键工程 ---> Build Path... ----> Configure Build Path ----> Java Build Path ----> 选中"Source"标签 ---->
点击"Add Folder..." ----> 选中scractchpad的子目录src -----> 点击"OK"

先行谢过

**Comment by qhm123** [comment]
Eclipse里面，Build Path -> Exclude可以忽略部分源码

在 2015年1月12日 星期一，上午10:31，LiYaHX 写道：

**Comment by LiYaHX** [comment]
OK. 

谢谢，我搞定了！哈哈哈！Thanks again~~~~
